############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "What We Do"
url = "what-we-do/"
weight = 2
hasChildren = true

  [[main]]
  parent = "What We Do"
  name = "Overview"
  url = "what-we-do/"
  weight = 1

  [[main]]
  parent = "What We Do"
  name = "BUILD"
  url = "what-we-do/build/"
  weight = 2

  [[main]]
  parent = "What We Do"
  name = "OPERATE"
  url = "what-we-do/operate/"
  weight = 3

  [[main]]
  parent = "What We Do"
  name = "TRANSFORM"
  url = "what-we-do/transform/"
  weight = 4

  [[main]]
  parent = "What We Do"
  name = "SECURE"
  url = "what-we-do/secure/"
  weight = 5

  [[main]]
  parent = "What We Do"
  name = "All Services"
  url = "services/"
  weight = 6

[[main]]
name = "How We Work"
url = "how-we-work/"
weight = 3

[[main]]
name = "Case Studies"
url = "case-studies/"
weight = 4

[[main]]
name = "About"
url = "about/"
weight = 5

[[main]]
name = "Contact"
url = "contact/"
weight = 6

# footer menu
[[footer]]
name = "What We Do"
url = "what-we-do/"
weight = 1

[[footer]]
name = "Services"
url = "services/"
weight = 2

[[footer]]
name = "About"
url = "about/"
weight = 3

[[footer]]
name = "Trust Center"
url = "trust/"
weight = 4

[[footer]]
name = "Contact"
url = "contact/"
weight = 5

[[footer]]
name = "Imprint"
url = "imprint/"
weight = 6

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 7
